spring:
  mail:
    host: smtp.gmail.com
    port:  587
    username: abhisheksinghbaghel8@gmail.com
    password: gsbaukadmiabjrdm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
